### ISSUE TITLE
Area of Interest Issues

### ISSUE THREAD

**Issue by xavidelamo** [dfguerrerom/sepal_mgci#7]
EDIT 12/11/2021: Editing this issue to have a clear and focused discussion. 

> @xavidelamo: List of countries and subnational divisions: Please ensure that the list of names exactly matches with the M49 standard (see https://unstats.un.org/unsd/methodology/m49/). The list of level 1 & 2 subnational division should also be consistent with the divisions available in the latest UN guidance on maps (see https://unfao.sharepoint.com/sites/OCCP/UN%20Maps/Forms/AllItems.aspx).

> @xavidelamo: Character enconding: The current encoding doesn't represent well non-English characters (for example, letters with diacritics or non-English letter are not shown at all) so it makes it sometimes difficult to recognize the name of the province/region in question.

**Comment by 12rambau** [comment]
Some of this point are actually not related directly to the `sepal-mgci` tool but rather the lib it uses to create the AOI selector. I'll try my best to adress them: 

>3- List of countries and subnational divisions: Please ensure that the list of names exactly matches with the M49 standard (see https://unstats.un.org/unsd/methodology/m49/). The list of level 1 & 2 subnational division should also be consistent with the divisions available in the latest UN guidance on maps (see https://unfao.sharepoint.com/sites/OCCP/UN%20Maps/Forms/AllItems.aspx).

The list is GEE based in this module so it's using the FAO GAUL 2015 dataset. (https://developers.google.com/earth-engine/datasets/catalog/FAO_GAUL_2015_level2?hl=en). To my knowledge that is the only dataset available on GEE that can address our requirement: full description of every subdivision in the world from level 0 to 2. If you want to use other dataset they need to be made publicly available in GEE as SEPAL is not embedding any data. 

>4- Character enconding: The current encoding doesn't represent well non-English characters (for example, letters with diacritics or non-English letter are not shown at all) so it makes it sometimes difficult to recognize the name of the province/region in question.

the areas names have been exported directly from GEE that does not support anything out of UTF8 specification. every specific character were replaced by a square. they are all listed in the following file https://www.github.com/12rambau/sepal_ui/master/sepal_ui/scripts/gaul_database.csv so if you see anything you can modify it, we gladly accept PR.

>5- Please replace:
>- "Select AOI" -> "Select Area of Interest"
>- "Country/Province" -> "Country or Area"
>- "Admin level 1" -> "Sub-national - Level 1"
>- "Admin level 2" -> "Sub-national - Level 2"
>- "Asset name"" -> "Google Earth Engine Asset"
>- "Select these inputs"-> "Select"

The AOI selection panel meets 1 big requirement of SEPAL: being available on cellphones and small screens. In the main framework they have decided to use these names so I'll stay consistent with the rest of the platform for now.
@dfguerrerom if you want to change them for this specific module you can still create a `CustomAoiTile`. I opened an issue for the one I can change : https://github.com/12rambau/sepal_ui/issues/270

I hope it helps

**Comment by xavidelamo** [comment]
Thanks for your comments, @12rambau 

I have checked the FAO GAUL dataset in more detail and have found that its use for SDG reporting is problematic as it is not consistent ​with UN methodology for statistics reporting, including the standard country and area classification ([M49 standard](https://unstats.un.org/unsd/methodology/m49/)). 

Basically, at first glance, the FAO GAUL seems to include a much larger list of territories, some of them not formally recognized at such by the UN. I haven't check the spatial country boundaries of the dataset so I can't tell if this component of the dataset also has issues.

This could potentially create problems with member countries due to the incorrect designation or improper involvement of some disputed territories in FAO activities (see [Administrative Circular 2021/13](https://intranet.fao.org/fileadmin/user_upload/FAO_Communications/ac/AC_2021-13.pdf) regarding increasing number of complains from member nations)

This is therefore relevant not only for the **sepal-mgci** but also for any other SEPAL-based tool aimed to support SDG reporting or other UN reporting processes.

However, I can't see an obvious solution to the problem, as the official spatial dataset that has been provided to us for such matters (see this [link](https://unfao.sharepoint.com/sites/OCCP/UN%20Maps/Forms/AllItems.aspx) is not available in GEE and I am not sure if it can be made openly available.  

This is something you may want to raise to Yelena and Erik.

**Comment by 12rambau** [comment]
@xavidelamo you're not the first one to raise this issue. Restoration applications such as se.plan, sdg 15.3.1...etc are facing the same problem of administrative boundaries.

As you mention we are facing a real issue here: the application developed for SEPAL are openly available so the core functionalities (such as selecting countries in a list) can only be based on openly available datasets. We asked to get the most recent one available from an API: long story short, they said "no". 
Until we manage to have these data available (publicly on GEE or via an API), we won't be able to retrieve them. A way to use it anyway is to download the data you need from your side and upload an .shp in the dropdown menu as you would do on any other GIS software. 

@dfguerrerom I think we should continue this conversation internally with the rest of the development team as it will be raised again.

**Comment by xavidelamo** [comment]
@12rambau I understand. I think we should stress that the decision of not making the spatial dataset openly available is limiting our capacity to support countries to report against SDG indicators. It would be good to understand the reasons why they don't want to make the dataset available to see if we can find some sort of workaround to solve the issue. This decision also spreads confusion outside the UN system because external users have no other option than using an outdated dataset such as the FAO GAUL as the most authoritative global admin layer available. Anyway, I'm  happy to help to solve this issue in anyway I can.

I agree that uploading the .shp file will solve the issue. 

@dfguerrerom A quick fix could be simply to subset the list of countries shown in the dropdown menu by selecting the countries and territories of FAO GAUL included in the M49 list only. This can be done via the ISO3 code (this field is present in both the M49 list and FAO GAUL). This is not perfect because I noticed that there are a few countries & territories included in the M49 list have not associated ISO3 code in FAO GAUL (Sudan, South Sudan, Falklands-Malvinas, etc.) but will get rid of many of the problematic territories (Taiwan, etc.) Happy to discuss further if needed.

**Comment by eriklindquist** [comment]
OK...jumping in here. @xavidelamo, do you know who we need to talk to about elevating this issue to find a solution? Maybe I will speak with the HiH geospatial people? The FAO / Google MoU and inclusion of GAUL in GEE was supposed to solve issues such as this...I thought. Anyway, I am happy there is a workaround for the applications...but we still need to get SEPAL as compliant as possible.
